name: OCR Workflow

on:
  workflow_dispatch:  

jobs:
  ocr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr poppler-utils
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run OCR script
        run: |
          python main.py
          cat converted_file.txt

      - uses: actions/upload-artifact@v4
        with:
          name: converted_file
          path: ./converted_file.txt

      
